### PR TITLE
Fix #343

### LINKED ISSUE #343: redirected to NOTHING
Hi there,
the `WebCralers` redirect handling code is confuding me a little bit. There will be the redirect url be calculated. If the result is `null` just a warning is printed "redirected to NOTHING" and the method returns immediately.
I am using the crawler to verify no broken links nor redirects at my page. This behaviour bugs my because there is no way to handle it probably and I think it's a "problem" in my scenario because the redirect leads to nothing.
Thanks for your help and advice.

### PR DESCRIPTION
**Pull request by s17t**

### CODE REVIEW

File: crawler4j/src/main/java/edu/uci/ics/crawler4j/crawler/CrawlController.java [hunk 1]
```diff
@@ -155,6 +155,21 @@ public Parser getParser() {
         T newInstance() throws Exception;
     }
 
+    private static class SingleInstanceFactory<T extends WebCrawler>
```
Comment (yasserg) [inline crawler4j/src/main/java/edu/uci/ics/crawler4j/crawler/CrawlController.java]: How is this related to the rest of the patch?

Comment (s17t) [reply crawler4j/src/main/java/edu/uci/ics/crawler4j/crawler/CrawlController.java]: I missed to push test. See PR.
